import Head from "next/head";
import styles from '../styles/header.module.css'
import Link from "next/link";
import Image from "next/image";
import { Raleway } from "next/font/google";
const raleway = Raleway({ weight: "500", subsets: ["latin"] });

export default function header() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div style={{backgroundColor: "#212526"}} className={raleway.className}>
                <header className={styles['header']}>
                    <nav className={styles['nav']}>
                        <img src="./logo.png" />
                        <p className={styles['timeP']}>Время работы: 10:00–20:00</p>
                        <div>
                            <p className={styles['timeP']}>+7 495 120-32-14</p>
                            <Link className={styles['zakas']} href='#'>Заказать звонок</Link>
                        </div>
                        <div className={styles['header-buttons']}>
                            <Link className={styles['links']} href='#'><img src="./heart.png" /></Link>
                            <Link className={styles['links']} href='#'><img src="./statistic.png" /></Link>
                            <Link className={styles['links']} href='/sign-in'><img src="./user.png" /></Link>
                            <Link className={styles['links']} href='#'><img src="./shopping-cart.png" /></Link>
                            <div className={styles['summa']}>
                                <p className={styles['timeP']}>Товаров на сумму</p>
                                <p className={styles['timeP']}>2 000 ₽</p>
                            </div>
                        </div>
                    </nav>
                </header>
            </div>
        </>
    );
}
